---
- name: Add the backports repo for debian
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present
    filename: backports

- name: Install opensmtpd from backports
  ansible.builtin.apt:
    name:
      - opensmtpd
    state: present
    update_cache: True
    default_release: buster-backports

- name: Install other required (non-backport) packages
  ansible.builtin.apt:
    name:
      - python3-cryptography
      - unattended-upgrades
    state: present

- name: Create the opensmtpd configuration files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item  }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - aliases
    - smtpd.conf
  notify:
    - reload_smtpd
